Build: Fix Watcom compile error
Now that Watcom is built with __MSDOS__ set we need to use non Turbo C
specific WORDREGS.

Fixes:
  find_str.c(111): Error! E1031: Name 'flags' not found in struct/union
                   WORDREGS